### ISSUE TITLE
imaging having this issue stuck on ur home page...

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/SelfHostedGIT#1]
https://git-scm.com/ is git
written by Linus Torvalds originally

he might come after you for using the name Git and making a knockoff

**Comment by Hardwaregore** [comment]
its a ui wrapper for git [facepalm]

**Comment by Hardwaregore** [comment]
# AAAAAAAAHHHHHHHH NONONONONONONONONONONONONONONONONONONONONONOOOOOOOOOOO 

# THEY BLOCKED GITHUB!!!!!!!!! (im using kasm)

**Comment by TechDudie** [comment]
well sux 2 be u ahahaaaaaaaha send me a photo and ill believe it

maybe if you were politur

or maybe they blocked it because kasm is on there in the first place

**Comment by Hardwaregore** [comment]
# YAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAY IT ISNT BLOCKED ANYMORE!!!!!!!!!!!!!!!!!

**Comment by TechDudie** [comment]
☹

From: Hardwaregore ***@***.***>
Date: Friday, October 28, 2022 at 8:42 AM
To: Hardwaregore/SelfHostedGIT ***@***.***>
Cc: TechnoDotΩ ***@***.***>, Author ***@***.***>
Subject: Re: [Hardwaregore/SelfHostedGIT] uhhhh... this isnt a git server (Issue #1)
YAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAYAY IT ISNT BLOCKED ANYMORE!!!!!!!!!!!!!!!!!

**Comment by Hardwaregore** [comment]
# EMOTIONAL DAMAGE
